library:
  source-dirs: src
tests:
  m-hs-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - m-hs
copyright: 2019 M Language
maintainer: aedan.smith@outlook.com
dependencies:
- directory
- transformers
- mtl
- hashmap
- HUnit
- haskeline
- parsec
- filepath
- generic-deriving
- comonad
- base >= 4.7 && < 5
name: m-hs
version: 0.1.0.0
extra-source-files:
- README.md
author: M Language
github: m-language/m
license: BSD3
executables:
  m-hs-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - m-hs
description: Please see the README on GitHub at <https://github.com/m-language/m>
