resolver: lts-14.14

packages:
- .

extra-deps:
- parsec-3.1.13.0
- mtl-2.2.2
- haskeline-0.7.4.3
- HUnit-1.6.0.0
- hashmap-1.3.3
- transformers-0.5.6.2
- directory-1.3.3.0
- filepath-1.4.2.1
- generic-deriving-1.13
- comonad-5.0.6
